# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171113_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
