# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171121_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ra',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
